aliases: []
creation_timestamp: 1751901671780
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1751901671780
metrics: null
model_id: m-de5a97016bdf40768ef9d17aaaeaf273
name: goemotions-model
params: null
run_id: 477da64ce526402ebfb1d2f427d9aa38
run_link: null
source: models:/m-de5a97016bdf40768ef9d17aaaeaf273
status: READY
status_message: null
storage_location: file:///C:/Scolarité/Efrei/M1/mental-health-checkin/mlflow/557569894523483552/models/m-de5a97016bdf40768ef9d17aaaeaf273/artifacts
user_id: null
version: 1
