name: Staging Build & Test

on:
  push:
    branches:
      - staging

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc
      - name: Download dataset
        run: |
          mkdir -p data
          https://raw.githubusercontent.com/aliciiaalb/mental-health-checkin/data/goemotions.csv -O data/goemotions.csv


      - name: Reproduce pipeline
        run: dvc repro

      - name: Run unit and integration tests
        run: pytest
